language: go

go:
  - 1.9.x
  - master

env:
  - TZ="Etc/UTC"

gobuild_args: -tags=integration -race -ldflags "-X github.com/jcmturner/awsfederation/app.version=v0.0.1 -X github.com/jcmturner/awsfederation/app.buildtime=`date -u '+%FT%TZ'` -X github.com/jcmturner/awsfederation/app.buildhash=`git rev-parse HEAD`"

sudo: required

services:
  - docker

before_install:
  - sudo /etc/init.d/mysql stop
  - docker pull mariadb
  - docker pull vault
  - docker run -d -v /etc/localtime:/etc/localtime:ro --rm --name mariadb -e MYSQL_ROOT_PASSWORD=rootpasswd -p 3306:3306 mariadb
  - docker run -d --cap-add=IPC_LOCK -v /etc/localtime:/etc/localtime:ro -e VAULT_DEV_ROOT_TOKEN_ID=roottoken -p 8200:8200 -e --rm --name vault vault
  - sleep 5
  - curl -s -X POST -H "X-Vault-Token:roottoken" -d '{"type":"app-id"}' http://127.0.0.1:8200/v1/sys/auth/app-id
  - curl -s -X PUT -H "X-Vault-Token:roottoken" -d '{"rules":"path \"secret/*\" { policy = \"write\" }"}' http://127.0.0.1:8200/v1/sys/policy/devtest
  - curl -s -X POST -H "X-Vault-Token:roottoken" -d '{"value":"devtest", "display_name":"devapp"}' http://localhost:8200/v1/auth/app-id/map/app-id/6a1ab78a-0f5b-4287-9371-cca1fc70b0f1
  - curl -s -X POST -H "X-Vault-Token:roottoken" -d '{"value":"6a1ab78a-0f5b-4287-9371-cca1fc70b0f1"}' http://localhost:8200/v1/auth/app-id/map/user-id/06ba5ac6-3d85-43df-81b5-cf56f4f4624e


