Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.define "datahost", primary: true do |datahost|
    datahost.vm.hostname = "data.host"
    datahost.vm.box = "centos/7"
    datahost.vm.network "private_network", ip: "10.80.137.90", netmask: "255.255.0.0"
    datahost.vm.provision :shell, path: "bootstrap.sh"
  end
end
