Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.define "mariadb", primary: true do |mariadb|
    mariadb.vm.hostname = "host.test.gokrb5"
    mariadb.vm.box = "centos/7"
    mariadb.vm.network "private_network", ip: "10.80.137.90", netmask: "255.255.0.0"
    mariadb.vm.provision :shell, path: "bootstrap.sh"
  end
end
